### ISSUE TITLE
Undefined jinja variable

### ISSUE THREAD

**Issue by jaykumar2001** [saltstack-formulas/java-formula#7]
Any idea whats causing the following error?  Thanks in advance.

```
2013-11-27 15:34:12,526 [salt.state                                  ][CRITICAL] Rendering SLS java.server_jdk failed, render error: Undefined jinja variable; line 3 in template

---
{% set java = pillar.get('java', {}) -%}
{% set jdk = java.get('jdk') -%}
{% set home = jdk.get('home', '/opt') -%}    <======================

server_jdk_tar:
  file.managed:
{%- if jdk['source'] is defined %}
    - name: {{ home }}/server_jdk.tgz
[...]

---
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/state.py", line 1944, in render_state
    rendered_sls=mods
  File "/usr/lib/python2.6/site-packages/salt/template.py", line 69, in compile_template
    ret = render(input_data, env, sls, **render_kwargs)
  File "/usr/lib/python2.6/site-packages/salt/renderers/jinja.py", line 42, in render
    tmp_data.get('data', 'Unknown render error in jinja renderer')
SaltRenderError: Undefined jinja variable; line 3 in template

---
{% set java = pillar.get('java', {}) -%}
{% set jdk = java.get('jdk') -%}
{% set home = jdk.get('home', '/opt') -%}    <======================

server_jdk_tar:
  file.managed:
{%- if jdk['source'] is defined %}
    - name: {{ home }}/server_jdk.tgz
[...]

---
```

**Comment by noelmcloughlin** [comment]
#10
